#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0xa139692d, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x6e7f4f74, __VMLINUX_SYMBOL_STR(single_release) },
	{ 0xe5f29f12, __VMLINUX_SYMBOL_STR(seq_read) },
	{ 0x2698a4b0, __VMLINUX_SYMBOL_STR(seq_lseek) },
	{ 0x51eafc8e, __VMLINUX_SYMBOL_STR(param_ops_int) },
	{ 0x9d0d6206, __VMLINUX_SYMBOL_STR(unregister_netdevice_notifier) },
	{ 0xce426def, __VMLINUX_SYMBOL_STR(unregister_pernet_subsys) },
	{ 0xd2da1048, __VMLINUX_SYMBOL_STR(register_netdevice_notifier) },
	{ 0x1dd5c89c, __VMLINUX_SYMBOL_STR(register_pernet_subsys) },
	{ 0x6d0aba34, __VMLINUX_SYMBOL_STR(wait_for_completion) },
	{ 0xe0e9c731, __VMLINUX_SYMBOL_STR(wake_up_process) },
	{ 0x794cefcd, __VMLINUX_SYMBOL_STR(kthread_bind) },
	{ 0x324d8d5c, __VMLINUX_SYMBOL_STR(kthread_create_on_node) },
	{ 0x1ceea0ab, __VMLINUX_SYMBOL_STR(proc_mkdir) },
	{ 0x6656c2f7, __VMLINUX_SYMBOL_STR(kthread_stop) },
	{ 0xc6cbbc89, __VMLINUX_SYMBOL_STR(capable) },
	{ 0x4482cdb, __VMLINUX_SYMBOL_STR(__refrigerator) },
	{ 0xd5cadcdd, __VMLINUX_SYMBOL_STR(freezing_slow_path) },
	{ 0xfa66f77c, __VMLINUX_SYMBOL_STR(finish_wait) },
	{ 0xd62c833f, __VMLINUX_SYMBOL_STR(schedule_timeout) },
	{ 0x34f22f94, __VMLINUX_SYMBOL_STR(prepare_to_wait_event) },
	{ 0xcf2cea31, __VMLINUX_SYMBOL_STR(_raw_read_unlock_bh) },
	{ 0x50277348, __VMLINUX_SYMBOL_STR(_raw_read_lock_bh) },
	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0x21252e14, __VMLINUX_SYMBOL_STR(remove_proc_entry) },
	{ 0x7ab88a45, __VMLINUX_SYMBOL_STR(system_freezing_cnt) },
	{ 0xa1c76e0a, __VMLINUX_SYMBOL_STR(_cond_resched) },
	{ 0x4c4fef19, __VMLINUX_SYMBOL_STR(kernel_stack) },
	{ 0xba63339c, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_bh) },
	{ 0xf6ebc03b, __VMLINUX_SYMBOL_STR(net_ratelimit) },
	{ 0x1637ff0f, __VMLINUX_SYMBOL_STR(_raw_spin_lock_bh) },
	{ 0x51d34997, __VMLINUX_SYMBOL_STR(skb_pull) },
	{ 0xa4ee571e, __VMLINUX_SYMBOL_STR(pskb_expand_head) },
	{ 0xb61cf87e, __VMLINUX_SYMBOL_STR(skb_push) },
	{ 0xb3f7646e, __VMLINUX_SYMBOL_STR(kthread_should_stop) },
	{ 0x9e61bb05, __VMLINUX_SYMBOL_STR(set_freezable) },
	{ 0x4b06d2e7, __VMLINUX_SYMBOL_STR(complete) },
	{ 0xf432dd3d, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0xc8b57c27, __VMLINUX_SYMBOL_STR(autoremove_wake_function) },
	{ 0x64afd19d, __VMLINUX_SYMBOL_STR(xfrm_stateonly_find) },
	{ 0x7a2af7b4, __VMLINUX_SYMBOL_STR(cpu_number) },
	{ 0xa735db59, __VMLINUX_SYMBOL_STR(prandom_u32) },
	{ 0x9c55cec, __VMLINUX_SYMBOL_STR(schedule_timeout_interruptible) },
	{ 0x3bd1b1f6, __VMLINUX_SYMBOL_STR(msecs_to_jiffies) },
	{ 0x360d049b, __VMLINUX_SYMBOL_STR(proc_create_data) },
	{ 0x9e0c711d, __VMLINUX_SYMBOL_STR(vzalloc_node) },
	{ 0xe914e41e, __VMLINUX_SYMBOL_STR(strcpy) },
	{ 0xaba7ca74, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_node_trace) },
	{ 0x2c451e50, __VMLINUX_SYMBOL_STR(__alloc_pages_nodemask) },
	{ 0x52215358, __VMLINUX_SYMBOL_STR(node_data) },
	{ 0xc31fb85, __VMLINUX_SYMBOL_STR(__get_page_tail) },
	{ 0xfb578fc5, __VMLINUX_SYMBOL_STR(memset) },
	{ 0x690b2cbe, __VMLINUX_SYMBOL_STR(skb_put) },
	{ 0x3aaa96d3, __VMLINUX_SYMBOL_STR(hrtimer_start_range_ns) },
	{ 0xf8c2d66, __VMLINUX_SYMBOL_STR(hrtimer_cancel) },
	{ 0x87b7ec5e, __VMLINUX_SYMBOL_STR(hrtimer_init_sleeper) },
	{ 0xf4b6c232, __VMLINUX_SYMBOL_STR(hrtimer_init) },
	{ 0x1000e51, __VMLINUX_SYMBOL_STR(schedule) },
	{ 0x999e8297, __VMLINUX_SYMBOL_STR(vfree) },
	{ 0xe136a58f, __VMLINUX_SYMBOL_STR(proc_remove) },
	{ 0xafa33d24, __VMLINUX_SYMBOL_STR(__xfrm_state_destroy) },
	{ 0xd88656ed, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0xa11d68b3, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{  0x66da6, __VMLINUX_SYMBOL_STR(nf_register_hook) },
	{ 0xc9d7ec63, __VMLINUX_SYMBOL_STR(dev_get_by_name) },
	{ 0xd9a919f3, __VMLINUX_SYMBOL_STR(init_net) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x60231f70, __VMLINUX_SYMBOL_STR(nf_unregister_hook) },
	{ 0xfe7c4287, __VMLINUX_SYMBOL_STR(nr_cpu_ids) },
	{ 0xc0a3d105, __VMLINUX_SYMBOL_STR(find_next_bit) },
	{ 0x3928efe9, __VMLINUX_SYMBOL_STR(__per_cpu_offset) },
	{ 0xbd100793, __VMLINUX_SYMBOL_STR(cpu_online_mask) },
	{ 0x618911fc, __VMLINUX_SYMBOL_STR(numa_node) },
	{ 0xe323a126, __VMLINUX_SYMBOL_STR(__netdev_alloc_skb) },
	{ 0x7e0c1ec4, __VMLINUX_SYMBOL_STR(__alloc_skb) },
	{ 0x73740b9d, __VMLINUX_SYMBOL_STR(kfree_skb) },
	{ 0xaebba10c, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0xcc5005fe, __VMLINUX_SYMBOL_STR(msleep_interruptible) },
	{ 0x9fd7ec59, __VMLINUX_SYMBOL_STR(current_task) },
	{ 0xfc3492c1, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0xda3e43d1, __VMLINUX_SYMBOL_STR(_raw_spin_unlock) },
	{ 0x5a921311, __VMLINUX_SYMBOL_STR(strncmp) },
	{ 0xd52bf1ce, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x754d539c, __VMLINUX_SYMBOL_STR(strlen) },
	{ 0x28318305, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0xe57878a1, __VMLINUX_SYMBOL_STR(in6_pton) },
	{ 0xf6770391, __VMLINUX_SYMBOL_STR(mac_pton) },
	{ 0x54e4db34, __VMLINUX_SYMBOL_STR(put_page) },
	{ 0x61fb248a, __VMLINUX_SYMBOL_STR(node_states) },
	{ 0x1b6314fd, __VMLINUX_SYMBOL_STR(in_aton) },
	{ 0x9166fada, __VMLINUX_SYMBOL_STR(strncpy) },
	{ 0x44b1d426, __VMLINUX_SYMBOL_STR(__dynamic_pr_debug) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0xe2d5255a, __VMLINUX_SYMBOL_STR(strcmp) },
	{ 0x91715312, __VMLINUX_SYMBOL_STR(sprintf) },
	{ 0x4f6b400b, __VMLINUX_SYMBOL_STR(_copy_from_user) },
	{ 0x11f7ed4c, __VMLINUX_SYMBOL_STR(hex_to_bin) },
	{ 0x91831d70, __VMLINUX_SYMBOL_STR(seq_printf) },
	{ 0x3fb8a666, __VMLINUX_SYMBOL_STR(seq_puts) },
	{ 0x31fa954f, __VMLINUX_SYMBOL_STR(single_open) },
	{ 0xa6c2b12d, __VMLINUX_SYMBOL_STR(PDE_DATA) },
	{ 0xc87c1f84, __VMLINUX_SYMBOL_STR(ktime_get) },
	{ 0x53569707, __VMLINUX_SYMBOL_STR(this_cpu_off) },
	{ 0x167e7f9d, __VMLINUX_SYMBOL_STR(__get_user_1) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=";


MODULE_INFO(srcversion, "3CE02FD586F3CEA0DE67A3B");
